### ISSUE TITLE
Tracking progress

### ISSUE THREAD

**Issue by tz70s** [tz70s/gpuflow#3]
The label `T1-T3` represents the priority from highest to lowest. 

**CLI Parsing** `T3`
- [x] `gflow install` for compiling in python CLI
- [x] Set up huge page @sychangww1121 
- [x] Configurable lcore and nics 
- [x] Pass args in C++ program 
- [x] Remove redundant script

**Testing** `T1`
- [x] Verify IPv6 lpm functionalities (use ping6 and associated ipv6 settings, expect equivalent to ipv4 ping test) @sychangww1121 

**GPU Side** `T2`
- [x] CUDA environment. @sychangww1121 
- [x] Ipv4 l3 forwarding core
  - [x] Compilation and Integration
  - [x] Async Packet copy
  - [x] Packet fields parsing
  - [x] LPM lookup
- [x] Ipv6 standalone progress in #13 , @r05921104  

**Profiling** `T1` @r05921104 
- [x] Helper module to call pktgen in python CLI ( May use **Lua script** for deeper configuration )
  * Requirements : configurable num of threads, target nic, target ip_address (v4, v6) 
- [x] Statistics collection module for receiving packets in time
- [x] Profiling PCI latency, context switch time, single packet processing latency, lpm look up memory latency. 
- [x] Intel VTune or valgrind for analysis. @sychangww1121 

**Platform** `T3`
- [x] Better to have platform portability, code is still runnable if no cuda is provided. (cpu)

@r05921104 , @sychangww1121 , pick up some todos!

**Comment by tz70s** [comment]
Finished, close. @r05921104 @sychangww1121
